version: '2'
services:
    ebaypricer-app:
        image: ebaypricer
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://ebaypricer-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=ebaypricer
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ebaypricer-mongodb:
        extends:
            file: mongodb.yml
            service: ebaypricer-mongodb
